### ISSUE TITLE
Typo in BluetoothChatFragment

### ISSUE THREAD

**Issue by MrStrong** [googlesamples/android-BluetoothChat#18]
`* Establish connection with other divice`

https://github.com/googlesamples/android-BluetoothChat/blob/master/Application/src/main/java/com/example/android/bluetoothchat/BluetoothChatFragment.java#L358

**Comment by amatt13** [comment]
Should this issue not be closed since commit the last commit?
(3e23e29cf0594af0b1425bd59b520e124085d5bf) 
Establish connection with other divice --> Establish connection with other device
